### ISSUE TITLE
python3-distutils missing therefore docker build fails. 

### ISSUE THREAD

**Issue by fireeee** [ufoym/deepo#38]
Please add python3-distutils:
`
+++ b/generator/modules/python.py
@@ -34,6 +34,7 @@ class Python(Module):
             DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
                 python3.6 \
                 python3.6-dev \
                 python3-distutils \
                 && \
`
Otherwise the container rocks.Good job and thanks for the effort.

Cheerz

**Comment by ufoym** [comment]
Could you explain why python3-distutils should be added?
Distutils seems the standard tool in Python.

**Comment by fireeee** [comment]
@ufoym   for `python generate.py Dockerfile python==3.6` the get-pip.py fails

`Traceback (most recent call last):
  File "/root/get-pip.py", line 20649, in <module>
    main()
  File "/root/get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "/root/get-pip.py", line 82, in bootstrap
    import pip._internal
  File "/tmp/tmpnedr_k8d/pip.zip/pip/_internal/__init__.py", line 42, in <module>
  File "/tmp/tmpnedr_k8d/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
  File "/tmp/tmpnedr_k8d/pip.zip/pip/_internal/index.py", line 25, in <module>
  File "/tmp/tmpnedr_k8d/pip.zip/pip/_internal/download.py", line 35, in <module>
  File "/tmp/tmpnedr_k8d/pip.zip/pip/_internal/locations.py", line 10, in <module>
ImportError: cannot import name 'sysconfig'
`

and all that happens before `pip install setuptools`. 

so the short answer is get-pip.py needs distutils

Cheerz

**Comment by ufoym** [comment]
Thank you for your information & solution.
We have resolved this issue in another way:
https://github.com/ufoym/deepo/commit/a6551b5ec645373d94ea7f244c767a2afb3fce0c

**Comment by sunavc** [comment]
If `python3-distutils` or `python3-distutils-extra` is not required, then the corresponding lines should be removed from `generator/modules/python.py`. Latest commit version `147f68670dc19aa15763b4654948126016cef349` causes `docker build` to throw an error if `--ubuntu-ver 16.04` is supplied to `generate.py` because line 40 in `generator/modules/python.py` should be `'-extra' if not self.composer.ubuntu_ver.startswith('18.') else '',` for `docker build` to succeed.
